name: nickesselman-nl
services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    depends_on: [php]
    ports:
      - "127.0.0.1:3010:80"   # keep 3010 now that we freed it
    volumes:
      - ./site:/srv/site
      - ./Caddyfile:/etc/caddy/Caddyfile

  php:
    image: php:8.2-fpm-alpine
    restart: unless-stopped
    volumes:
      - ./site:/srv/site
